public enum NodeClass
{
	MINIRE_PROGRAM("MINIRE-PROGRAM"), STATEMENT_LIST("STATEMENT-LIST"), STATEMENT("STATEMENT"), STATEMENT_LIST_TAIL("STATEMENT-LIST-TAIL"), FILE_NAMES("FILE-NAMES"), SOURCE_FILE("SOURCE-FILE"), DESTINATION_FILE(
			"DESTINATION-FILE"), EXPRESSION_LIST("EXP-LIST"), EXPRESSION_LIST_TAIL("EXP-LIST-TAIL"), EXPRESSION("EXP"), EXPRESSION_TAIL("EXP-TAIL"), TERM("TERM"), FILE_NAME("FILE-NAME"), BINARY_OPERATOR(
			"BIN-OP"), BEGIN("BEGIN"), END("END"), ASSIGN("ASSIGN"), REPLACE("REPLACE"), WITH("WITH"), IN("IN"), TO("TO"), SEMICOLON("SEMICOLON"), PRINT("PRINT"), RPAREN("RPAREN"), LPAREN("LPAREN"), COMMA(
			"COMMA"), POUND("POUND"), FIND("FIND"), PLUS("PLUS"), MINUS("MINUS"), MULTIPLY("MULTIPLY"), DIVIDE("DIVIDE"), DIFF("DIFF"), UNION("UNION"), INTERS("INTERS"), ID("ID"), INTNUM("INTNUM"), MAXFREQSTRING(
			"MAXFREQSTRING"), REGEX("REGEX"), ASCII_STR("ASCII_STR"), OUTPUT_FILE("OUTPUT_FILE"), EMPTY("EMPTY"), NULL("NULL");

	private String	ClassName;


	private NodeClass(String className)
	{
		ClassName = className;
	}


	public String toString()
	{
		return ClassName;
	}
}
